/**
 * @mainpage BitWeaving-lib Documentation
 *
 * @section description_sec Description
 * The code implements a library for performing efficient scanning queries over column oriented data stores.
 *
 * @section usage_sec Usage
 * To build and run the lib, you need the following packages:
 * <ul>
 *  <li>A modern C++ compiler
 *  <li>Doxygen 1.6 or higher (for generating documentation only)
 * </ul>
 *
 * To write a program using Bitweaving lib, compile Bitweaving lib into a library
 * and link your program with it. Run:
 * @code
 *  $ make
 * @endcode
 * to compile the lib, and generate the lib file libbitweaving.so. Once you are
 * able to compile the bitweaving library, you should link libbitweaving.so into
 * your program, and make sure you have $(BITWEAVING_DIR)/include in the header
 * search path so that the compiler can find all public header files when compiling
 * your program. See $(BITWEAVING_DIR)/examples for some example program to use
 * the bitweaving library.
 *
 * To run unit tests, run:
 * @code
 *  $ make test
 *  $ bitweaving-test
 * @endcode
 *
 * Documentation is generated by Doxygen. To generate the documentation, run:
 * @code
 *  $ make doc
 * @endcode
 * Resulting documentation will be placed in the <code>docs/</code> directory;
 * open <code>index.html</code> with your web browser to view it.
 *
 * @section file_layout_sec File layout
 * The files in this package are organized under the following hierarchy:
 * <pre>include/</pre>
 * The header files in include directory (include/*.h) contains all public interface to the public callers.
 *
 * <pre>src/</pre>
 * The internal implementation of this library is in this directory. The public callers should not include and rely on the header/scource files in this directory. Those internal interfaces may be changed without warnings.
 *
 * <pre>test/</pre>
 * Unit test code.
 *
 * <pre>example/</pre>
 * Some example code that shows how to use these public APIs to implement various functions.
 *
 * <pre>docs/</pre>
 * Generated documentation.
 */
